scheduled-messages:
  interval-minutes: 3
  messages:
      - "§e[🔔] 默认聊天为队伍聊天，你可以使用 /s <内容> 进行喊话"
      - "§e[🔔] 如果50格内有敌人，你不能打开共享背包或传送菜单"
      - "§e[🔔] 游戏开始30分钟后，将不允许新玩家加入"
glass-frozen-time: 30
waiting-time: 60
spawn-distance: 300
